### ISSUE TITLE
Building on Fedora linux

### ISSUE THREAD

**Issue by bkmgit** [microsoft/SymCrypt#26]
Default build options need some changes when packaging for Fedora Linux.
For a release build, following test fails:
```
Starting performance measurements...
Perf min measurement clock time = 30000
Sanity check measurements:
512.0 cycles fixedTimeLoop, 6.0 cycles null, 39.0 cycles (for 32), 71.0 cycles (for 64), 135.0 cycles (for 128), 263.0 cycles (for 256), 519.0 cycles (for 512), 1030.9 cycles (for 1024), 2054.7 cycles (for 2048), 4103.1 cycles (for 4096), 8198.2 cycles (for 8192), 16391.6 cycles (for 16384)
*

***** FATAL ERROR /builddir/build/BUILD/SymCrypt-103.1.0/unittest/lib/perf.cpp(670): Measurement too fast
error: Bad exit status from /var/tmp/rpm-tmp.KJeasA (%check)
```
[Build log](https://download.copr.fedorainfracloud.org/results/fed500/SymCrypt/fedora-rawhide-x86_64/05281000-SymCrypt/builder-live.log.gz)

FIPS verification also seems to fail with a debug build:
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/SymCrypt-103.1.0/scripts/process_fips_module.py", line 402, in <module>
    main()
  File "/builddir/build/BUILD/SymCrypt-103.1.0/scripts/process_fips_module.py", line 365, in main
    assert(fips_boundary_variable.value == PLACEHOLDER_VALUE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
make[2]: *** [modules_linux/generic/CMakeFiles/symcrypt_generic_linux.dir/build.make:149: module/generic/libsymcrypt.so.103.1.0] Error 1
make[2]: *** Deleting file 'module/generic/libsymcrypt.so.103.1.0'
make[1]: *** [CMakeFiles/Makefile2:328: modules_linux/generic/CMakeFiles/symcrypt_generic_linux.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.2aryKX (%build)
```

[Build log](https://download.copr.fedorainfracloud.org/results/fed500/SymCrypt/fedora-rawhide-x86_64/05280976-SymCrypt/builder-live.log.gz)

Can investigate further if of interest to see how SymCrypt can be adapted to other platforms.

**Comment by NielsFerguson** [comment]
First one could be due to the compiler being more aggressive in inlining and optimizing and not performing all the computations in the performance measurement loop.

Niels

From: Benson Muite ***@***.***>
Sent: Saturday, January 21, 2023 9:46
To: microsoft/SymCrypt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/SymCrypt] Building on Fedora linux (Issue #26)


Default build options need some changes when packaging for Fedora Linux.
For a release build, following test fails:

Starting performance measurements...

Perf min measurement clock time = 30000

Sanity check measurements:

512.0 cycles fixedTimeLoop, 6.0 cycles null, 39.0 cycles (for 32), 71.0 cycles (for 64), 135.0 cycles (for 128), 263.0 cycles (for 256), 519.0 cycles (for 512), 1030.9 cycles (for 1024), 2054.7 cycles (for 2048), 4103.1 cycles (for 4096), 8198.2 cycles (for 8192), 16391.6 cycles (for 16384)

*



***** FATAL ERROR /builddir/build/BUILD/SymCrypt-103.1.0/unittest/lib/perf.cpp(670): Measurement too fast

error: Bad exit status from /var/tmp/rpm-tmp.KJeasA (%check)

Build log<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownload.copr.fedorainfracloud.org%2Fresults%2Ffed500%2FSymCrypt%2Ffedora-rawhide-x86_64%2F05281000-SymCrypt%2Fbuilder-live.log.gz&data=05%7C01%7Cniels%40microsoft.com%7C50f0714fde584aa91eb008dafbd76d3d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638099199920115459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CD8IPZTA3e%2FpvUC3qHBgAyLj%2BosnAtYFMDNCAWG3S2Q%3D&reserved=0>

FIPS verification also seems to fail with a debug build:

Traceback (most recent call last):

  File "/builddir/build/BUILD/SymCrypt-103.1.0/scripts/process_fips_module.py", line 402, in <module>

    main()

  File "/builddir/build/BUILD/SymCrypt-103.1.0/scripts/process_fips_module.py", line 365, in main

    assert(fips_boundary_variable.value == PLACEHOLDER_VALUE)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError

make[2]: *** [modules_linux/generic/CMakeFiles/symcrypt_generic_linux.dir/build.make:149: module/generic/libsymcrypt.so.103.1.0] Error 1

make[2]: *** Deleting file 'module/generic/libsymcrypt.so.103.1.0'

make[1]: *** [CMakeFiles/Makefile2:328: modules_linux/generic/CMakeFiles/symcrypt_generic_linux.dir/all] Error 2

make: *** [Makefile:91: all] Error 2

error: Bad exit status from /var/tmp/rpm-tmp.2aryKX (%build)

Build log<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownload.copr.fedorainfracloud.org%2Fresults%2Ffed500%2FSymCrypt%2Ffedora-rawhide-x86_64%2F05280976-SymCrypt%2Fbuilder-live.log.gz&data=05%7C01%7Cniels%40microsoft.com%7C50f0714fde584aa91eb008dafbd76d3d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638099199920115459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ixTV7%2BzKmIjBUH6wSFJhsU7oXQgwbRvLpdTmvudUl7k%3D&reserved=0>

Can investigate further if of interest to see how SymCrypt can be adapted to other platforms.

-

**Comment by mlindgren** [comment]
Fedora isn't currently a priority for us, but if you happen to find out what the issue is, we'd be happy to make reasonable changes to improve our cross-distro support. The interesting thing is that we do have a package which builds for Mariner using their build environment; Mariner is RedHat/Fedora based, and I believe the Mariner build tools should be similar to what's used there. Possibly just different default compiler flags - we may need to be more explicit in choosing which flags we set or don't set.
